### ISSUE TITLE
Error: one or more of debug, error, info, trace, warn ranges overlap

### ISSUE THREAD

**Issue by andresv** [knurling-rs/defmt#135]
I tried to setup `defmt` for an old project.
I took `lib.rs` straight from https://github.com/knurling-rs/app-template/blob/main/src/lib.rs and modified `config.toml` according to this: https://github.com/knurling-rs/app-template/blob/main/.cargo/config.toml

My `Cargo.toml` looks more or less like this:
```toml
...
name = "um8"
...

[dependencies.defmt]
git = "https://github.com/knurling-rs/defmt"
branch = "main"

[dependencies.defmt-rtt]
git = "https://github.com/knurling-rs/defmt"
branch = "main"

[dependencies]
panic-halt = "0.2"
cortex-m = "0.6.3"
cortex-m-rt = "0.6.12"
embedded-hal = "0.2"
cortex-m-rtic = "0.5"
...

[[bin]]
name = "um8"
test = false
bench = false

[lib]
name = "defmtlib"
path = "src/lib.rs"
test = false
bench = false

[features]
# set logging levels here
default = [
    "defmt-default",
    #"some_module/defmt-debug",
]
# do NOT modify these features
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[profile.dev]
opt-level = 1
codegen-units = 16
debug = 1
lto = 'fat'

[profile.release]
opt-level = 2 # optimize for speed
codegen-units = 1 # better optimizations
debug = 1 # symbols are nice and they don't increase the size on Flash
lto = 'fat'
```

Notice that `src/lib.rs` is named to `defmtlib`.
`main.rs` looks like this:
```rust
...
use defmtlib as _; // src/lib.rs
...
#[init(spawn = [blinky])]
    fn init(mut ctx: init::Context) -> init::LateResources {
        defmt::info!("Hello, world!");
        //defmt::warn!("Hello, world!");
        //defmt::error!("Hello, world!");
```

Logging works with `error!` and `warn!` but not with `info!` `debug!`, `trace!`:
```
Error: one or more of debug, error, info, trace, warn ranges overlap
```
