### ISSUE TITLE
`binfmt-macros`: fix logging level filter logic

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#16]
To match the spec. Currently, the logic looks like this:

``` rust
if cfg!(feature = "binfmt-on") {
    if binfmt::export::Level::Info >= binfmt::export::threshold() {
```

this is not quite right because `threshold` in defined in `binfmt` and we want the log statement to be filtered based on the Cargo feature of the *crate calling into the macro* so instead we need something like this for info!:

``` rust
if cfg!(feature = "binfmt-on") &&
    (cfg(feature = "binfmt-info") ||
        (!cfg(feature = "binfmt-warn") && !cfg(feature = "binfmt-error"))) {
```

`binfmt-warn` means only WARN level and up.
`binfmt-error` means only ERROR level and up.
If only `binfmt-on` is enabled then INFO level is logged regardless of the state of `debug_assertions`
The `debug!` macro will need to include a `cfg!(debug_assertions)` somewhere.
Logging levels will likely need to be "cascaded" in the Cargo.toml of the caller crate to make the above work:

``` toml
[features]
binfmt-on = []
binfmt-trace = ["binfmt-debug", "binfmt-info", "binfmt-warn", "binfmt-error"]
binfmt-debug = ["binfmt-info", "binfmt-warn", "binfmt-error"]
binfmt-info = ["binfmt-warn", "binfmt-error"]
binfmt-warn = ["binfmt-error"]
binfmt-error = []
```

If we need that then the user documentation will need to be updated.

Or there may be a different way to set this up.
