### ISSUE TITLE
Linking with GCC GCs DEFMT_LOG_STATEMENT symbols

### ISSUE THREAD

**Issue by mattico** [knurling-rs/defmt#180]
rustc 1.48.0-nightly (ef663a8a4 2020-09-30)
gcc version 9.3.1 20200408 (release) (GNU Arm Embedded Toolchain 9-2020-q2-update)

When running with `probe-run --defmt` I always see ```  (HOST) WARN  insufficient DWARF info; compile your program with `debug = 2` to enable location info``` and no messages are printed. However I am configured to produce debuginfo and I can see the debuginfo and defmt sections in the binary.

My `.cargo/Config.toml`:

```toml
[target.thumbv7em-none-eabihf]
runner = "probe-run --chip stm32h743bi --defmt"

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)
rustflags = [
  "-C", "linker=arm-none-eabi-gcc",
  "-C", "link-arg=-Wl,-Tlink.x",
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-specs=nano.specs",
  "-C", "link-arg=-lc",
  "-C", "link-arg=-mcpu=cortex-m7",
  "-C", "link-arg=-mfpu=fpv5-d16",
  "-C", "link-arg=-mfloat-abi=hard",
  "-C", "link-arg=-mthumb",
  "-C", "link-arg=-Wl,-Tdefmt.x",
  "-C", "link-arg=-g",
  "-C", "inline-threshold=225",
]

[unstable]
features = ["host_dep"]
```

My `Cargo.toml`:

```toml
[features]
default = ["defmt-default"]
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[profile.release]
codegen-units = 1 # better optimizations
opt-level = 3
debug = 2 # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations

[profile.dev.package."*"]
opt-level = "s"
```

Adding logging to defmt_elf2table I can see that all of the `DEFMT_LOG_STATEMENT` symbols have been GCd.

Any suggestions?
