### ISSUE TITLE
add `version = ..` to dependencies

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#236]
to be able to publish defmt on crates.io all the crates in this repo need to depend on their crates.io version. That means that dependencies that look like in the Cargo.toml like this:

``` toml
[dependencies]
defmt-macros = { path = "macros" }
```

should look like this:

``` toml
[dependencies]
defmt-macros = { path = "macros", version = "0.1.0" } # add version field
```

the specified version needs to match the current version of the crate. As everything will be release for the first, "0.1.0" should be used everywhere
