### ISSUE TITLE
turn CI logic into xtasks

### ISSUE THREAD

**Issue by japaric** [knurling-rs/defmt#366]
would be nice if there were xtasks to run the CI tests locally.
right now CI logic is in a yaml file that contains bash-like stuff and the tests.sh bash file (which won't run on Windows)
Ideally I would like the GHA yaml be more or less just a call of different xtasks
``` yaml
# apt-get install stuff has been omitted
jobs:
  host:
    # omitted: OS matrix
    name: run unit tests on the host
    run: cargo xtask test host

  cross:
    name: check cross compilation
    run: cargo xtask test cross

  snapshot:
    name: run snapshot tests (QEMU)
    run: cargo xtask test snapshot

  book:
    name: run mdbook tests
    run: cargo xtask test book

  lint:
    name: run rustfmt and clippy
    run: cargo xtask test lint
```

and then a single xtask, e.g. `cargo xtask test all`, that sort of runs all the above jobs which is what contributors would run locally to check their branch / PR is "green".
the xtasks should auto-install the cross compilation targets (`rustup target add`) so that contributors don't need to do "setup" steps
(maybe the xtasks should uninstall the cross compilation targets that were not there when they exit, regardless of the exit code)
