### ISSUE TITLE
It's impossible to support multiple versions of defmt in a crate

### ISSUE THREAD

**Issue by jonas-schievink** [knurling-rs/defmt#426]
If you do this:

```toml
[dependencies]
defmt01 = { version = "0.1.0", package = "defmt", optional = true }
defmt02 = { version = "0.2.0", package = "defmt", optional = true }
```

it results in Cargo complaining:

```
error: failed to select a version for `defmt`.
    ... required by package `bxcan v0.4.0 (/home/jonas/dev/bxcan)`
versions that meet the requirements `^0.1.0` are: 0.1.3, 0.1.2, 0.1.1, 0.1.0

the package `defmt` links to the native library `defmt`, but it conflicts with a previous package which links to `defmt` as well:
package `defmt v0.2.0`
    ... which is depended on by `bxcan v0.4.0 (/home/jonas/dev/bxcan)`
```

This is because defmt makes use of the `links` key in Cargo.toml to prevent linking multiple versions of it into the same executable. It looks like Cargo handles this very poorly and demands that even optional dependencies don't use the same `links` directive (we should probably check if this is a Cargo bug).
